name: flood
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - geopandas
  - gdal
  - pip
  - python
  - psutil
  - remotezip
  - s5cmd
  - shapely
  - tqdm
  - xarray
  - zarr
  - pip:
    - asf-search