name: flood
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - geopandas
  - git
  - gdal
  - libgdal-arrow-parquet
  - pip
  - python=3.13
  - psutil
  - pyarrow
  - remotezip
  - s3fs
  - s5cmd
  - shapely
  - tqdm
  - xarray
  - zarr
  - pip:
    - asf-search
    - botocore
    - git+https://github.com/MikeFHS/automated-rating-curve.git
    - git+https://github.com/RickytheGuy/curve2flood.git